spring:
  application:
    name: ai-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  bucket-name: ai-project-487201-face-bucket # Change this to your actual bucket name

logging:
  level:
    com.ai.backend: DEBUG
